server:
  port: 9090

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    #    schema: # schema.sql中一般存放的是DDL脚本，即通常为创建或更新库表的脚本
    #      - classpath:sql/schema.sql
    #    data: classpath:sql/data.sql # data.sql中一般是DML脚本，即通常为数据插入脚本
    #    initialization-mode: always # spring某个版本之后需要加上这句，否则不会自动执行sql文件
    #    separator: $$
    hikari:
      auto-commit: true
      connection-timeout: 10000
      idle-timeout: 300000
      max-lifetime: 600000
      minimum-idle: 5
      maximum-pool-size: 20

mybatis:
  type-aliases-package: com.chens.coblog.domain
  mapper-locations: classpath:mapper/*.xml

